@startuml name

package "Presentation Layer" {
    class MainWindow {
        + controllers
        + show_page()
    }

    class Page1 {
        + diary_controller
        + build_ui()
    }
    class Page2 {
        + diary_controller
        + build_ui()
    }
}

package "Business Logic Layer" {
    class DiaryController {
        + save_diary_entry()
        + get_diary_list()
        + navigate_to_page()
    }
}

package "Data Access Layer" {
    class DiaryModel {
        + get_diary_list()
        + save_diary_entry()
    }
}

MainWindow --> DiaryController : "Calls"
DiaryController --> DiaryModel : "Calls"

MainWindow -> Page1 : "Navigates"
MainWindow -> Page2 : "Navigates"

@enduml
