@startuml name
skinparam packageStyle rectangle

' モジュールをパッケージとして定義
package "main.py" {
    [main関数]
    [Appクラス]
}

package "controllers.py" {
    [DiaryControllerクラス]
}

package "models.py" {
    [BaseModelクラス]
    [DiaryModelクラス]
}

package "windows.py" {
    [MainWindowクラス]
}

package "pages.py" {
    [BasePageクラス]
    [Page1クラス]
    [Page2クラス]
}

database "sample.db" as DB

' 依存関係を定義
[main関数] --> [Appクラス]
[Appクラス] --> "controllers.py"
[Appクラス] --> "models.py"
[Appクラス] --> "windows.py"
[Appクラス] --> "pages.py"

"controllers.py" --> "models.py"
"windows.py" --> "controllers.py"
"windows.py" --> "pages.py"

"pages.py" --> "controllers.py"
"models.py" --> DB
@enduml
