@startuml name

' クラス定義
class MainWindow {
    - controllers: dict[str, コントローラクラス]
    + __init__(pages, controllers: dict[str, Any])
    + show_page(page_name: str)
}

class DiaryController {
    - diary_model: DiaryModel
    + __init__(diary_model: DiaryModel)
    + get_list_data(): str
    + get_one(id: int): str
}

class DiaryModel {
    - t_diary: テーブル名
    + get_all(): list[sqlite3.Row]
    + get_one(id:int): list[sqlite3.Row]
}

class Page1 {
    - diary_controller: DiaryController
    + __init__(master: ctk.CTk, controllers: dict[str, Any])
    + build_ui(): void
    + msg_output(page_num: int): void
}

class Page2 {
    - diary_controller: DiaryController
    + __init__(master: ctk.CTk, controllers: dict[str, Any])
    + build_ui(): void
    + msg_output(page_num: int): void
}

' クラスの関連性を表す
MainWindow o-- Page1 : 管理
MainWindow o-- Page2 : 管理
MainWindow --> DiaryController : 使用
DiaryController --> DiaryModel : 使用
Page1 --> DiaryController : 使用
Page2 --> DiaryController : 使用

@enduml
